name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # - name: Set up Python
            #   uses: actions/setup-python@v2
            #   with:
            #       python-version: '3.x'

            - name: build image
              run: |
                  docker build -t pythonapp:latest .
                  docker tag pythonapp:latest pythonapp:dev
                  docker run -d -p 8060:5000 pythonapp:dev

            
            
    deploy-ECR: 
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: ecr credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:  
                role-to-assume: arn:aws:iam::$${secrets.AWS_ACCOUNT_ID}:role/$${secrets.ECR_ACCESS_ROLE}
                aws-region: $${secrets.AWS_REGION}

            - name: Push to ECR
              run: |
                    docker push $${secrets.AWS_ACCOUNT_ID}.dkr.ecr.$${secrets.AWS_REGION}.amazonaws.com/pythonapp:latest

               